<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6B0KB3N" failures="1" tests="1" name="Edge Test" time="48.22" errors="0" timestamp="2025-02-18T15:02:39 IST">
  <testcase classname="classes.TestDataDriven" name="executeTestSteps" time="29.77">
    <failure type="java.lang.AssertionError" message="Test failed due to an exception for element: //img[@src=&amp;apos;https://qa-navyojna.epps-erp.in/assets/HR.svg&amp;apos;]">
      <![CDATA[java.lang.AssertionError: Test failed due to an exception for element: //img[@src='https://qa-navyojna.epps-erp.in/assets/HR.svg']
at classes.TestDataDriven.executeTestSteps(TestDataDriven.java:110)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- executeTestSteps -->
</testsuite> <!-- Edge Test -->
